// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace WispTestProject
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        #region Properties
        public UIWISPПодключитевашихсWindow UIWISPПодключитевашихсWindow
        {
            get
            {
                if ((this.mUIWISPПодключитевашихсWindow == null))
                {
                    this.mUIWISPПодключитевашихсWindow = new UIWISPПодключитевашихсWindow();
                }
                return this.mUIWISPПодключитевашихсWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIWISPПодключитевашихсWindow mUIWISPПодключитевашихсWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIWISPПодключитевашихсWindow : BrowserWindow
    {
        
        public UIWISPПодключитевашихсWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "WISP - Подключите ваших сотрудников к корпоративной жизни";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("WISP - Подключите ваших сотрудников к корпоративной жизни");
            this.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIWISPПодключитевашихсDocument UIWISPПодключитевашихсDocument
        {
            get
            {
                if ((this.mUIWISPПодключитевашихсDocument == null))
                {
                    this.mUIWISPПодключитевашихсDocument = new UIWISPПодключитевашихсDocument(this);
                }
                return this.mUIWISPПодключитевашихсDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIWISPПодключитевашихсDocument mUIWISPПодключитевашихсDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIWISPПодключитевашихсDocument : HtmlDocument
    {
        
        public UIWISPПодключитевашихсDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "WISP - Подключите ваших сотрудников к корпоративной жизни";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://agaveqa.inside.cactussoft.biz/";
            this.WindowTitles.Add("WISP - Подключите ваших сотрудников к корпоративной жизни");
            this.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIВходENБезопасностьТаPane
        {
            get
            {
                if ((this.mUIВходENБезопасностьТаPane == null))
                {
                    this.mUIВходENБезопасностьТаPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIВходENБезопасностьТаPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIВходENБезопасностьТаPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIВходENБезопасностьТаPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Вход EN БезопасностьТарифы ";
                    this.mUIВходENБезопасностьТаPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIВходENБезопасностьТаPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "header-stripe";
                    this.mUIВходENБезопасностьТаPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"header-stripe\"";
                    this.mUIВходENБезопасностьТаPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "2";
                    this.mUIВходENБезопасностьТаPane.WindowTitles.Add("WISP - Подключите ваших сотрудников к корпоративной жизни");
                    this.mUIВходENБезопасностьТаPane.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIВходENБезопасностьТаPane;
            }
        }
        
        public HtmlDiv UIВходENБезопасностьТаPane1
        {
            get
            {
                if ((this.mUIВходENБезопасностьТаPane1 == null))
                {
                    this.mUIВходENБезопасностьТаPane1 = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIВходENБезопасностьТаPane1.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIВходENБезопасностьТаPane1.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIВходENБезопасностьТаPane1.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Вход EN БезопасностьТарифы \r\n\r\n\r\nСоздайт";
                    this.mUIВходENБезопасностьТаPane1.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIВходENБезопасностьТаPane1.FilterProperties[HtmlDiv.PropertyNames.Class] = "header-area";
                    this.mUIВходENБезопасностьТаPane1.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"header-area\"";
                    this.mUIВходENБезопасностьТаPane1.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "1";
                    this.mUIВходENБезопасностьТаPane1.WindowTitles.Add("WISP - Подключите ваших сотрудников к корпоративной жизни");
                    this.mUIВходENБезопасностьТаPane1.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIВходENБезопасностьТаPane1;
            }
        }
        
        public HtmlDiv UIФункционалПерсонализPane
        {
            get
            {
                if ((this.mUIФункционалПерсонализPane == null))
                {
                    this.mUIФункционалПерсонализPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIФункционалПерсонализPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIФункционалПерсонализPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIФункционалПерсонализPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Функционал:\r\n\r\nПерсонализируйте приложен";
                    this.mUIФункционалПерсонализPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIФункционалПерсонализPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "features-area";
                    this.mUIФункционалПерсонализPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"features-area\"";
                    this.mUIФункционалПерсонализPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "15";
                    this.mUIФункционалПерсонализPane.WindowTitles.Add("WISP - Подключите ваших сотрудников к корпоративной жизни");
                    this.mUIФункционалПерсонализPane.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIФункционалПерсонализPane;
            }
        }
        
        public HtmlDiv UIItem1ПерсонализацияСPane
        {
            get
            {
                if ((this.mUIItem1ПерсонализацияСPane == null))
                {
                    this.mUIItem1ПерсонализацияСPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItem1ПерсонализацияСPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItem1ПерсонализацияСPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItem1ПерсонализацияСPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "1\r\n\r\nПерсонализация\r\n\r\nСделайте ваше при";
                    this.mUIItem1ПерсонализацияСPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItem1ПерсонализацияСPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "slide-area";
                    this.mUIItem1ПерсонализацияСPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"slide-area\"";
                    this.mUIItem1ПерсонализацияСPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "17";
                    this.mUIItem1ПерсонализацияСPane.WindowTitles.Add("WISP - Подключите ваших сотрудников к корпоративной жизни");
                    this.mUIItem1ПерсонализацияСPane.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIItem1ПерсонализацияСPane;
            }
        }
        
        public HtmlHyperlink UIТарифыHyperlink
        {
            get
            {
                if ((this.mUIТарифыHyperlink == null))
                {
                    this.mUIТарифыHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIТарифыHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIТарифыHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIТарифыHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIТарифыHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Тарифы";
                    this.mUIТарифыHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/admin/";
                    this.mUIТарифыHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Тарифы";
                    this.mUIТарифыHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://agaveqa.inside.cactussoft.biz/admin/#/tariffplans";
                    this.mUIТарифыHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "pull-right cross-link";
                    this.mUIТарифыHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "title=\"Тарифы\" class=\"pull-right cross-l";
                    this.mUIТарифыHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "5";
                    this.mUIТарифыHyperlink.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIТарифыHyperlink;
            }
        }
        
        public HtmlHyperlink UIБезопасностьHyperlink
        {
            get
            {
                if ((this.mUIБезопасностьHyperlink == null))
                {
                    this.mUIБезопасностьHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIБезопасностьHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIБезопасностьHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIБезопасностьHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIБезопасностьHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Безопасность";
                    this.mUIБезопасностьHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/security";
                    this.mUIБезопасностьHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Безопасность";
                    this.mUIБезопасностьHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://agaveqa.inside.cactussoft.biz/security";
                    this.mUIБезопасностьHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "pull-right cross-link";
                    this.mUIБезопасностьHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "title=\"Безопасность\" class=\"pull-right c";
                    this.mUIБезопасностьHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "4";
                    this.mUIБезопасностьHyperlink.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIБезопасностьHyperlink;
            }
        }
        
        public HtmlHyperlink UIRUHyperlink
        {
            get
            {
                if ((this.mUIRUHyperlink == null))
                {
                    this.mUIRUHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIRUHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "lang";
                    this.mUIRUHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIRUHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIRUHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "RU";
                    this.mUIRUHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "void(0)";
                    this.mUIRUHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Choose your Language";
                    this.mUIRUHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "javascript:void(0)";
                    this.mUIRUHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "language active";
                    this.mUIRUHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "title=\"Choose your Language\" class=\"lang";
                    this.mUIRUHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "3";
                    this.mUIRUHyperlink.WindowTitles.Add("Wisp - Connect your employees to your company’s life");
                    #endregion
                }
                return this.mUIRUHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIВходENБезопасностьТаPane;
        
        private HtmlDiv mUIВходENБезопасностьТаPane1;
        
        private HtmlDiv mUIФункционалПерсонализPane;
        
        private HtmlDiv mUIItem1ПерсонализацияСPane;
        
        private HtmlHyperlink mUIТарифыHyperlink;
        
        private HtmlHyperlink mUIБезопасностьHyperlink;
        
        private HtmlHyperlink mUIRUHyperlink;
        #endregion
    }
}
